_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": lr-AdamW
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.8.20
            "5": 0.18.5
            "6": 4.45.2
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
